### ISSUE TITLE
Plugings using wasm

### ISSUE THREAD

**Issue by gedw99** [ipfs/kubo#10054]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

RE: https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#plugins

Wazero is 100% golang and can run wasm on anything. even mobile.

Making plugins that are compiled to wasm is pretty easy these days, as well as how they are exposed.

for a P2P system it also means that you don't need to trust the plugins because they are sandboxed.

lots of wazero frameworks out there too: https://github.com/tetratelabs/wazero/blob/main/site/content/community/users.md?plain=1

The best one that i use is https://docs.timecraft.dev

- code: https://github.com/stealthrocket/timecraft

- can be bound to file systme or network with decent control.

**Comment by Jorropo** [comment]
@gedw99 we are not intrested in wasm for the sake of having wasm.

We would review each plugin usecase one by one. What would like to do with a wasm plugin ?

**Comment by Jorropo** [comment]
Note about https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#plugins, this can't work for wasm plugins, this is using golang's builtin [`plugin`](https://pkg.go.dev/plugin) system, this is not cross ABI compatible, you can't load a wasm plugin into an amd64 binary, this isn't easily 1 to 1 mappable since our code internally relies on reflection and type assertions.

We don't have the resource to enginer a complex solution that would modify go's runtime to permit to do that.

Thus that why if usecases needs to be viewed one by one.

**Comment by gedw99** [comment]
P2p computing where you bring the compute to the data .

**Comment by aschmahmann** [comment]
> P2p computing where you bring the compute to the data .

@gedw99 building off of @Jorropo's comments above you can **already** build a number of different plugins using these interfaces https://github.com/ipfs/kubo/blob/master/docs/plugins.md#plugin-types and have the plugin use a WASM runtime and dynamically load and execute code for you if you'd like. So if you're looking for something more that would mean describing something specific in order to match.

>  My issue is specific & actionable.

For example:
- Maybe you wanted an IPLD plugin type like https://github.com/ipfs/kubo/pull/9016, which means that the issue is defining an IPLD codec and/or ADL ABI
- Maybe you want a way to hook up custom CLI commands in Go so you can leverage IPVM (https://github.com/ipvm-wg/) or some other tool to execute WASM for a defined ABI (although presumably you could also just leverage stock kubo or build a boxo-based binary to do something similar)
- ...

Which is why

> Here we are looking for API and technical designs of what we would implement.

If you're looking for more general community feedback on what using kubo + WASM together might look like https://discuss.ipfs.tech/ or some of the community chat channels are probably better places to start.
