### ISSUE TITLE
Cannot find machine-readable HTTP API spec

### ISSUE THREAD

**Issue by matthiasbeyer** [ipfs/kubo#10522]
### Checklist

- [X] I am reporting a documentation issue in this repo, not https://docs.ipfs.tech.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

I cannot find the HTTP API specification in machine readable format. The website (https://docs.ipfs.tech/reference/kubo/rpc/#getting-started) seems to be auto-generated, which is why I assume that there must be some machine-readable format (something like an openapi specification), but I cannot find it. Maybe it is not linked to prominently enought?

**Comment by gammazero** [comment]
Unfortunately it is not feasible to represent this using OpenAPI due to the inconsistency across the API, and this would require a highly custom API spec for each endpoint and parameter. A 3rd party is welcome to provide such a machine-readable description, but this is not something the IPFS maintainers will be providing and maintaining in the near future.

if you are interested in generating an API spec, you may find this documentation tool useful:
https://github.com/ipfs/ipfs-docs/tree/main/tools/http-api-docs

What is the main purpose for which you would like a machine-readable API spec? Is there a specific language that you are interested in generating client for?

**Comment by matthiasbeyer** [comment]
> What is the main purpose for which you would like a machine-readable API spec? Is there a specific language that you are interested in generating client for?

Yes, Rust. But I figured, I'd go one level lower into the stack and use libp2p (which is available in Rust) for my idea.

**Comment by matthiasbeyer** [comment]
Still relevant.

**Comment by matthiasbeyer** [comment]
Reopen this @github-actions
