### ISSUE TITLE
Restart daemon from 5001 UI console

### ISSUE THREAD

**Issue by bn-c** [ipfs/kubo#10528]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

This is a QoL improvement request.

I am running IPFS node on a remote VPS, with SSH tunneling to use it's api locally. Is there a way for me to restart the node remotely as well instead of having to switch to my shell to manually terminate daemon process and restart it?

**Comment by bn-c** [comment]
Ok, after a quick read from the RPC protocol documentation, it appears that implementation will require api change... 
I am not sure if this is related to a protocol enhancement suggestion. If so, feel free to close this issue! 😄

**Comment by lidel** [comment]
We do not have "restart" command because it requires higher level orchestration, but we do have CLI [`ipfs shutdown`](https://docs.ipfs.tech/reference/kubo/cli/#ipfs-shutdown) / RPC [`/api/v0/shutdown`.](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-shutdown)

If you are running your remote node in Docker, you can run it with [`--restart unless-stopped`](https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy) and then if you call `shutdown` over RPC, your node will shut down, and Docker orchestrator will restart it once it detects the daemon is no longer running.

Hope this helps! :)
