### ISSUE TITLE
ipfs/kubo:master-latest docker causing error

### ISSUE THREAD

**Issue by ehsan6sha** [ipfs/kubo#10558]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.tech](https://discuss.ipfs.tech/c/help/13).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [kubo version](https://dist.ipfs.tech/#kubo) or have an issue updating.

### Installation method

built from source

### Version

```Text
Kubo version: 0.32.0-dev-56c68a1
Repo version: 16
System version: arm64/linux
Golang version: go1.23.2
```

### Description

the latest update starts to show
Error: invalid or no prefix in shard identifier: �������������������������������������

even when started fresh

**Comment by gammazero** [comment]
### Check Config
It seems like something is wrong with the config in the Docker container. Are you using the default config? If you are, the config should be located in the container at `/data/ipfs/config`. Could you post the output from the command:
```
docker exec -ti <container_id> /bin/cat /data/ipfs/config 
```

### Error Detail
The error come from [here](https://github.com/ipfs/go-ds-flatfs/blob/master/shard.go#L85) because the shard identifier above does not start with "/repo/flatfs/shard/".

Kubo calls this from the flatfs plugin, [here](https://github.com/ipfs/kubo/blob/master/plugin/plugins/flatfs/flatfs.go#L62), getting the shard identifier from the "shardFun" parameter in the fsrepo datastore config. Normally the config should contain something like:
```
 "Datastore": {                                                                                                           
    "Spec": {                                                                                                              
      "mounts": [                                                                                                          
        {                                                                                                                  
          "child": {                                                                                                       
            "path": "blocks",                                                                                              
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",                                                           
            "sync": true,                                                                                                  
            "type": "flatfs"                                                                                               
          },                                                                                                               
          "mountpoint": "/blocks",                                                                                         
          "prefix": "flatfs.datastore",                                                                                    
          "type": "measure"                                                                                                
        },
```
