### ISSUE TITLE
Options to disable un-wanted features

### ISSUE THREAD

**Issue by cbluth** [ipfs/kubo#6329]
#### Version information:
```
root@a2:~# ipfs version --all
go-ipfs version: 0.4.20-
Repo version: 7
System version: arm/linux
Golang version: go1.12.4
root@a2:~# 
```

#### Type:
- "enhancement ": If you'd like to suggest an improvement on to existing feature.

#### Description:
Please allow configuration options to disable unnecessary things like the web-ui, http-gateway, and perhaps anything else in order to reduce resource usage.

**Comment by magik6k** [comment]
If you remove `Addresses.Gateway` from config, the gateway won't start listening, but that won't really affect resource usage much. Disabling webui is not currently possible, and it's probably not worth it as the handler code will be in memory anyways, so that option would only free few KB of memory at most.

You may want to apply the low-power [config profile](https://github.com/ipfs/go-ipfs/blob/fdbd501f6fcf7d217bc0a6ff0cb49af475646b2c/docs/config.md#profiles) - `ipfs conifg profile apply lowpower` to reduce resource use.

**Comment by gl-yziquel** [comment]
Disabling web-ui is worth it. For instance if you have other services running on port 8080, and you don't want to spend hours finding config options. Simply disabling web-ui allows for smoother multitasking when setting up infrastructure. My 2 cents.

**Comment by Jorropo** [comment]
@gl-yziquel webui is a collection of static files on `localhost:5001/ipfs/...` and a 302 HTTP response on `localhost:5001/webui`
8080 is the gateway and as stated in this comment https://github.com/ipfs/kubo/issues/6329#issuecomment-492273761 you can turn it off.
(you can also turn off the API by removing `Addresses.API` too)

**Comment by gl-yziquel** [comment]
Thank you for the information.
