### ISSUE TITLE
Avoid truncating blocks over 2MiB in object commands

### ISSUE THREAD

**Issue by Stebalien** [ipfs/kubo#7019]
#### Version information:
> master

#### Description:

Instead of truncating objects, we should return an _error_ when the user tries to put a block over 2MiB.

**Comment by kevincox** [comment]
Discusson from #7018:

I don't have an example. But protobufs don't detect truncation. So if you ran the following command, and it managed to cut the proto between fields (most likely between two links, or after the links but before the data field) then no error would be detected.

```
curl -vF file=@/tmp/myproto.pb "http://localhost:5001/api/v0/object/put?pin=true&inputenc=protobuf"
```

**Comment by ribasushi** [comment]
@kevincox that's sufficient, thanks!

**Comment by kevincox** [comment]
Note: I don't think JSON or XML are vulnerable to this because the detect truncation. (The decoder will notice the lack of a `}` or `</Node>` but the error returned is quite confusing.

**Comment by lidel** [comment]
`ipfs object` APIs have been deprecated (https://github.com/ipfs/kubo/issues/7936) since 2021, but we've added  `ipfs object put --allow-big-block` as safeguard at some point. 

More modern commands like `ipfs block put` and `ipfs dag put`  error when input is too big, and require passing `--allow-big-block` to proceed.  If there are any issues with them, that needs to be filled as a new issue.
