### ISSUE TITLE
Bitswap Testground In CI

### ISSUE THREAD

**Issue by Stebalien** [ipfs/kubo#8255]
We've written some testground tests for bitswap and data-transfer, but they were primarily for one-off benchmarking.

However, as we make changes, we need continuous testing to make sure we don't introduce regressions and/or break things. Testing in infra and one-off testing can help us catch some issues, but it isn't sufficient.

*Goal:* ensure there are no regressions, especially in setups we're unlikely to encounter through normal testing:

- High/low latency/bandwidth connections.
- Faulty links/nodes (e.g., nodes restart).
- Two nodes, 5 nodes, 20 nodes.

**Prior Art & Resources**

- Testground: https://github.com/testground/testground
- Lotus testplans: https://github.com/filecoin-project/lotus/tree/master/testplans
- Testground as a service (TaaS): https://ci.testground.ipfs.team/
- CircleCI setup for TaaS: https://github.com/filecoin-project/lotus/blob/master/.circleci/config.yml#L316
- Testground knowledge: @nonsense & @hacdias
- Testground in CI knowledge: @coryschwartz

**Acceptance Criteria**

1. CI integration. Ideally through GitHub Actions, but CircleCI is acceptable.
2. Ideally we'd use TaaS, but running testground in docker on CI is acceptable for the _basic_ tests we need.
3. A simple point-to-point data transfer testground test to verify that the setup works.

For simplicity, I recommend using bitswap directly instead of constructing a full IPFS node (better reproducibility).

**Future Tests**

Once everything "works", we should implement the following tests (to be broken out into separate issues later).

- Data transfer with:
    - High/low bandwidth/latency (matrix)
    - 2, 5, 20 nodes (matrix)
    - We're primarily looking to make sure we don't see any significant performance regressions.
- Data transfer between two nodes where the node serving the data restarts (verify that the test completes within a reasonable time period, TBD by the test).
- Data transfer between two nodes where the link is broken and restored (again, verify that the test completes).

**Comment by coryschwartz** [comment]
The PR I added adds a *very basic* testground plan as a github action, a similar action exists in the lotus repo.

I noticed there is a similar testplan in go-graphsync, if it makes sense, I can move this to the go-bitswap repo and maybe we can add some more top-line tests that run tests with the whole IPFS node.

This test doesn't currently take advantage of any of the networking features in testground, but I'd be happy to write some of those. It's possible in testground to setup, for example, firewall rules between each pod to simulate partial network unreachability, and it might be good to add more comprehensive real-world tests such as that.

Nevertheless, this inital PR can be merged just for the the github action.

**Comment by petar** [comment]
The ci<->testground system still needs to resolve a couple of design problems, before it becomes a reusable platform:
1. What is the standard way for emitting statistics from testplans, having in mind that the results have to be parsed automatically by an analysis tool? Two options are:
   1.1. use the unstructured logging in testground `runenv.RecordMessage(string)` and give it a JSON encoding of a predefined Go stats type
   1.2 use the go-log structured logging. It is unclear whether testground can collects these.
   More generally it in unclear to me what is the essential difference between using `runenv.RecordMessage` or `go-log` logging in a testplan. `go-log` provides better user-facing methods for logging structures, which is what we want to output from testplans.
2. In order to record results of past runs, CI needs access to some sort of persistent key-value database. Do git actions provide a mechanism for saving derived data associated with a commit? Or do we need an external database service?

**Comment by nonsense** [comment]
Regarding 1: There is a `metrics` API in the `sdk-go` of Testground - it provides a few types, such as `Counter`, `Gauge`, `Histogram`, etc.

These metrics can be periodically emitted to a database (for example we have an InfluxDB reporter), or saved to a file.

If you have InfluxDB / Grafana locally, it is pretty easy to use this feature.

---

Regarding 2: We currently don't have a persistent key-value database (or time-series database) attached to TaaS (https://ci.testground.ipfs.team/tasks) - this needs operational maintenance and in general more engineering effort.

---

I am interested in hearing ideas on how to improve this further once we have proper staffing to push TaaS and Testground to the next level.

**Comment by petar** [comment]
@coryschwartz @nonsense Given that TaaS does not provide persistence (as per @nonsense answer above), I think the next steps for this project are:

(a) Figure out if we can extract test results as soon as the testplan completes and save them in a dedicated github repo, where they can be accessed by future test runs for comparison.
(b) Pull the results from the testplan run of the latest previous go-ipfs tag and compare against them in CI.

For (a), there seems to be two possible directions:
- Use testground's metrics API. This may be too awkward because standing up an InfluxDB in CI seems too complex.
- Use `runenv.RecordMessage` or `go-log` to emit structured log messages with results; collect the testground logs after the experiment and parse out the logs we care about.

**Comment by coryschwartz** [comment]
We do already have an influx cloud account (testground is already capable of using influx), my thinking is that we can setup an installation there. The only downside I see is that we have unauthenticated usage. We would want to enable authentication to to ci.testground.ipfs.team so we don't have unauthenticated users (people who have forked lotus, for example) using up influxdb resources.

I'm not sure that we want unauthenticated testground users at all, if we do, then we would have to do something different, but I am thinking I am thinking we can simply hook up testground to influx cloud and then turn on authentication to TGAAS

**Comment by coryschwartz** [comment]
I wouldn't be opposed to collecting the outputs by adding them to the github repo that created the request, or even just pinning them sto ipfs somewhere.

**Comment by hacdias** [comment]
We haven't been using Testground for a long time and the tests have been since removed. I'm closing this.
