### ISSUE TITLE
Gateway: disable access to Cid-folder not through  subdomain  http://<cid>.ipfs.<gateway

### ISSUE THREAD

**Issue by shemeshg** [ipfs/kubo#8687]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

Since most users unaware that without subdomain all theire web storage is shared among other sites, and cause XSS.

See: https://docs.ipfs.io/how-to/address-ipfs-on-web/#dweb-addressing-in-brief

I’ve noticed in the documentation you referred to it as “more secure, harder to set up” but this minor extra difficulty could be crucial,

especially when developers tends to encrypt/protect the “ipfs data” and not the web storage (where they usually store private keys),  so steeling of encryption keys and data itself or tempering protected data  becomes far too easy.
or in most cases (like DWEB Dbs) occurs accidentally with no bad intension at all. 

* [!] This is also should be true for ```https://gateway.ipfs.io/ipns/<CID FOLDER>```

**Comment by Jorropo** [comment]
There are valid use case for non subdomain based requests, mainly outside of browsers.

If you are using `curl` or just an http client in whatever language.
`https://example.com/ipfs/<CID>` is:
- simpler
- faster (as HTTP/2 is faster if everything is under one domain)
- it works (some OS don't resolve the star under localhost: `*.localhost`, that actually IPFS companion doing that on them, in this case you can't use subdomains gateways with simple tools like `requests` or `curl`).

### Let's just filter out browsers from non subdomain ?

I don't think so, I've seen multiple people using IPFS gateways as webtorrent webseeds, then non subdomain is perfectly safe because webtorrent is just reading it as a blob of data and doing torrent thingies to it.

This is only an issue if you are setting your `window.origin` to it somehow because then all of the browser identity is shared.
In all other cases it should be fine (actually maybe someone loading code with the origin of the root gateway could create a service worker and intercept other requests done to the gateway and modify them, I'm not sure).

If something should be done I belive, we should disallow is things with unsafe origins, everything else seems OK to me.
(If that were might choice, this would be a WONTFIX, we can't unsure everyone does safe things)

**Comment by guseggert** [comment]
Path gateways won't be removed and subdomain gateways are only useful in browser contexts but introduce overhead (redirects, DNS lookups, etc.). If you don't want to run a path gateway, then I suggest you run Kubo behind a reverse proxy.
