### ISSUE TITLE
Improve sharness tests failure reports

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#8991]
It's very unclear which test fail.
The error message is not in the failing test (which is just a `grep failed`).
You need to deep dive through logs, CTRL + F `failed` (which will show other unrelated failures often).

**Comment by Stebalien** [comment]
There are two different issues here:

1. Sharness tests are a pain to write, maintain, etc. Especially if you don't know bash.
2. Our current CI setup doesn't parse sharness tests.

That second point is _much_ easier to fix. IIRC, we _had_ a way to export junit result files, but we're not currently using that.

**Comment by galargh** [comment]
It seems that the JUnit report we generate now are not valid but I might be able to do something about it.

**Comment by galargh** [comment]
Quick update:
I've been able to upgrade sharness, update our implementation of JUnit XML reports generation and add XML to HTML conversion. I've tested in on GitHub Actions and here are example reports that it spits out https://github.com/galorgh/kubo/actions/runs/3153345461 (note: errors = known breakages, failures = unknown breakages + fixed known breakages).

TODO:
- [ ] test JUnit XML generation on CircleCI
- [ ] update strings in html report to reflect how WE use JUnit (e.g. let's explicitly change `Errors` to `Known breakages` rather than leaving it up to the reader to know)
- [ ] make the GitHub Actions sharness workflow include results summary - https://github.com/marketplace/actions/test-reporter
- [ ] figure out how to publish the HTML one-pager so that one doesn't have to download and unzip it
- [ ] maybe (?) add failure type next to the `not ok` string

**Comment by BigLep** [comment]
> test JUnit XML generation on CircleCI

@galargh : do we need to do this?  If we are moved over to GitHub Actions this is no longer relevant right?  Basically, if this is more than 30minutes I wouldn't spend time on it from what I understand.

**Comment by galargh** [comment]
This should take definitely less than 30 minutes. I think it only entails ensuring that `xmllint` is installed on the machine where we run sharness.

**Comment by galargh** [comment]
The new reporting proposed in https://github.com/ipfs/kubo/pull/9355 will look like this:
- https://github.com/ipfs/kubo/actions/runs/3288358400/attempts/1#summary-9003264577
