### ISSUE TITLE
Circle CI not flipping green on some PR

### ISSUE THREAD

**Issue by Jorropo** [ipfs/kubo#9084]
It seems that when the PR is comming from:
- An organization.
- An account of someone who have circle CI configured.

The CI is not correctly reporting status. Example: #9069

This is a long bug we notice often. It's painfull and we should fix it.

**Comment by galargh** [comment]
According to CircleCI's blog (https://support.circleci.com/hc/en-us/articles/360008097173-Troubleshooting-why-pull-requests-are-not-triggering-jobs-on-my-organization-) it can happen when:
1. ❎ you revoked OAuth access to CircleCI on your VCS provider (GitHub, BitBucket)
1. ❓ you're following the fork instead of the upstream repo
1. ❎ the branch and the pull request happen to be created simultaneously

1 is definitely not the case because we wouldn't be getting any builds if that was the case.

3 is not it either because we don't have `Only build pull requests` turned on in CircleCI for `kubo`.

2 is possible but @2color said he didn't have runs in his account - https://github.com/ipfs/kubo/pull/9069#issuecomment-1175888207. @2color could you check if you have `go-ipfs` project set up in https://app.circleci.com/projects/project-dashboard/github/2color/? And if so, if you're following it? My theory is that it would be enough to block the original repo from running workflows, even if you don't have it configured to actually perform the runs.

Other possibility would be that GitHub lost some webhooks but given that there was quite a bit of activity on the PR this seems quite unlikely.

@Jorropo if you notice it again on some other PR, could you let me know? I'd like to investigate webhook logs.

**Comment by 2color** [comment]
I haven't set up a CircleCI account. This is what I have:

<img width="666" alt="Screen Shot 2022-09-13 at 2 17 00 PM" src="https://user-images.githubusercontent.com/1992255/189898692-539dfdb1-f062-4bd0-83df-19c169e50b1c.png">

**Comment by galargh** [comment]
Thanks for checking!

Btw, I also test opened two PRs, one from my priv account - https://github.com/ipfs/kubo/pull/9268 - and the other from my test org - https://github.com/ipfs/kubo/pull/9269 - and they both triggered runs as expected...

**Comment by Jorropo** [comment]
@galargh AFAIK it is reliably failing with *some* peoples, @2color could you please a new test pull request ?

**Comment by BigLep** [comment]
Closing as not planned given https://github.com/ipfs/kubo/issues/8804
