### ISSUE TITLE
Import file/folder with CID and data

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/kubo#9173]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/kubo/issues?q=is%3Aissue) for my issue.

### Description

It would be nice if I could supply a CID like a regular SHA hash and a file/folder and the corresponding data and have kubo fetch the necessary metadata for the CID and then import the data from the file.

### Rationale

It's pretty common to have an SHA-Sum and a URL currently, to fetch a file. But sometimes the URLs go offline.

If a [CID can replace the SHA-Sum](#9172) the user can download the URL and check the file with Kubo, without replacing any current toolset (except the hashing tool itself).

After the download, kubo could be instructed to import the downloaded file, by supplying the file and the CID to it's cache.

This way other people can fetch the file from the first user, if the URL is no longer available.

### Usecase in Lutris

I think that's the perfect usage of [Kubo in Lutris](https://github.com/lutris/lutris/issues/4414), where currently URLs and hashes are in use. The URLs would be fetched once with URL-Store. Which means in theory the data will be available through an IPFS-Node as a HTTP to IPFS proxy. But this will be very slow.

So the obvious the perfect solution would be to fetch the URL, as long as regular HTTP URLs are provided which work, put the data into the cache on the nodes which have downloaded them, to make the data widespread available and if the URL starts to fail just rely on the IPFS-Network for distribution.

### Usage

```
kubo import --file=/path/to/file /ipfs/CID
kubo import --ignore-auxiliary=1 --folder=/path/to/folder/ /ipfs/CID 
```

_(Where --ignore-auxiliary=1 in the folder version would ignore any additional files/folders like `.git`)_

```
kubo import /ipfs/CID
```

_Would work analog to `kubo get` where it would search in the `./$CID` folder for the file/folder structure._

**Comment by Pawa2101Taras** [comment]
https://ipfs.io/ipfs/QmSyQm2W6yWUPJtWYcktccn9fvmtgb7GFJw1X9y1CXzYLm

**Comment by Pawa2101Taras** [comment]
> https://ipfs.io/ipfs/QmSyQm2W6yWUPJtWYcktccn9fvmtgb7GFJw1X9y1CXzYLm
Помогите открыть уже мозг сломал нужна Фотка из этой ссылки можно скриншотом умоляю

**Comment by BigLep** [comment]
@RubenKelevra : we believe this connects to the discussion here: https://discuss.ipfs.tech/t/supporting-large-ipld-blocks/15093. 
 Until decisions get made there, this requested functionality won't be able to get implemented.  

@lidel is going to check is there is a duplicate issue we can link this to since this is not new desired functionality.

**Comment by lidel** [comment]
## Does not sound feasible

> So the obvious the perfect solution would be to fetch the URL, as long as regular HTTP URLs are provided which work, put the data into the cache on the nodes which have downloaded them, to make the data widespread available and if the URL starts to fail just rely on the IPFS-Network for distribution.

In this context, the proposal from this PR is not feasible, or at least feels unnecessarily overcomplicated.
Firstly, adding another import command will be UX footgun – we already have `dag import`,  how it is different from `ipfs add`? etc

Even if we add something like that, it won't work, because data is already provided by urlstore, and afaik, right now, we do not support having the same block in flatfs and urlstore at the same time. When  [urlstore](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipfs-urlstore) is used for a CID, its blocks are  marked as "present", but the data is not present locally, but fetched on-demand via range-requests from a remote URL.

## Reframing this feature request

@RubenKelevra let me know if I misunderstood you, but I think what you really propose here, is to essentially make urlstore more useful by doing fallback to regular datastore if the urlstore fails, and caching blocks fetched by urlstore in the regular datastore, so it acts as a hot cache. 

This is a valid feature request, but  requires design discussion and should be opened as a new issue – feel free to fill one, but make it clear you want to improve the utility of the urlstore.

As for non-urlstore use cases, let's continue in:
- large blocks (allowing use of original SHA sums) discussion at https://discuss.ipfs.tech/t/supporting-large-ipld-blocks/15093?u=lidel
-  "verifying" / "comparing" CID against data on disk – discussion happening in https://github.com/ipfs/kubo/issues/9172.

**Comment by RubenKelevra** [comment]
Yeah, this sounds like a good idea, too @lidel.

But the intent with this Feature Request was something different:

I like to have more flexibility with using the Content-ID as regular hash sum. So if I got a file locally or somewhere on the Internet and a Content-ID I like to be able to *proof* that the Content-ID is a match, like I'm currently able to do with a say SHA-Sum. 

The request UX-wise would also be not an "import" or an "add", but an "verify":

`kubo cid-verify $filename $cid` for example.
